-- DropForeignKey
ALTER TABLE "WEDDING_TmpTest" DROP CONSTRAINT "WEDDING_TmpTest_createdById_fkey";

-- AlterTable
ALTER TABLE "WEDDING_TmpTest" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "isActive" DROP NOT NULL,
ALTER COLUMN "createdById" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "WEDDING_TmpTest" ADD CONSTRAINT "WEDDING_TmpTest_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "WEDDING_User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
