name: CI

on: [push, pull_request]

env:
  PLAYGROUND_PRISMA_URL: https://example.com/
  NODE_ENV: CI
  NEXTAUTH_SECRET: xyz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
