name: CI

on: [push, pull_request]

env:
  PLAYGROUND_PRISMA_URL: https://example.com/
  NODE_ENV: PRODUCTION
  NEXTAUTH_SECRET: xyz
  NEXTAUTH_URL: https://example.com/
  DISCORD_CLIENT_ID: "123"
  DISCORD_CLIENT_SECRET: "123"
  ENV_SOURCE: ci.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
